language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
